### ISSUE TITLE
Lose state for http timeout, ECONNREFUSED, ECONNRESET

### ISSUE THREAD

**Issue by dimichgh** [othiym23/node-continuation-local-storage#24]
CLS seems to lose state when timeout or other connection error happens.
Only if I bindEmitter request object it would keep it.
This leads to modules that do http requests breaking CLS context when error occurs.
Can CLS do this automatically?

Here's test case:
```javascript
var http             = require('http')
  , createNamespace = require('../context').createNamespace
  ;

  var namespace = createNamespace('http');
  namespace.run(function () {
    namespace.set('test', 0xabad1dea);

    console.log('before: ', namespace.get('test'));
    // var req = http.get('http://127.0.0.1:8080', function (res) { // REFUSED
    var req = http.get('http://128.0.0.1:8080', function (res) { // TIMEOUT
        res.on('data', function (chunk) {
        });
        res.on('end', function () {
            console.log('response: ', namespace.get('test'));
        });
    });
    
    // namespace.bindEmitter(req);
    req.setTimeout(500, function() {
        console.log('timeout: ', namespace.get('test')); // >> undefined
        req.abort();
    });

    req.on('error', function(e) {
        console.log('abort: ', namespace.get('test'));// >> undefined
        console.log('error: ', e);
    });

    // write data to request body
    req.write('data\n');
    req.end();
});
```

**Comment by leedm777** [comment]
@othiym23 I understand that in general, binding to event emitters is hard. But speaking specifically about the use case of HTTP requests, it seems reasonable that events should be emitted in the same context in which the request was created. This is true for data, end, and error events for `ENOTFOUND` errors. Having some emitted errors lose context seems buggy.

I have a really [ugly test script](https://gist.github.com/leedm777/226ef34e44340990b0d0) that shows that in most cases, events are bound to the context in which the request was created. But for `ECONNREFUSED` errors, they are not.

If I shim both `http.request()` and `https.request()`, I can work around the problem.

```
shimmer.wrap(http, 'request', function (request) {
    return function () {
        var res = request.apply(this, arguments);
        ns.bindEmitter(res);
        return res;
    };
});

shimmer.wrap(require('https'), 'request', function (request) {
    return function () {
        var res = request.apply(this, arguments);
        ns.bindEmitter(res);
        return res;
    };
});
```

**Comment by othiym23** [comment]
> binding to event emitters is hard

It's not "hard", it's _expensive_. All of the commonly-used EventEmitter code paths have been tuned within an inch of their lives to work efficiently in V8, and wrapping them up in closures has a performance impact that can range from unnoticeable to unforgivably high, depending on the application. Because this overhead is rarely noticeable until your application is already under heavy load, it feels like a bad call to opt users of CLS into this path automatically. `async-listener`'s overhead is unavoidable, but this isn't.

`newrelic` did add both the `IncomingMessage` (`req`) and the `ServerResponse` (`res`) as emitters to bind to the CLS context (both for error monitoring and for state propagation), and there are middlewares floating around for CLS that will do the same for Express / Restify and Hapi. That's probably the best way to shim this in. If you want to shim it in globally (if, for instance, you're running without a framework), that's an appropriate decision for you as the app developer to make, and maybe it would be nice to have a standard shim exposed via the CLS API to simplify that process. But turning it on automatically is a baaaad idea.

My basic attitude towards CLS, formed by watching what has happened with `domains` in Node, is that it should be doing as little as possible and shouldn't try too hard to be a batteries-included API. This makes it less accessible, which isn't great, but it also keeps people from inadvertently causing themselves severe and hard-to-diagnose production issues down the road.

**Comment by dimichgh** [comment]
@othiym23 I agree with your statement. We were able to reduce number of CLS namespaces used in our stack which improved performance. 
We also bindAll callback or request where we deal with connection either http or DB (mongo or couchbase). Having a single place of control for any http connection (registry) helped and now we do not see this problem and no Q/promise patching is needed. Just make sure you have require for CLS as a first statement in your startup script.

**Comment by leedm777** [comment]
@othiym23 

> `newrelic` did add both the `IncomingMessage` (`req`) and the `ServerResponse` (`res`) as emitters to bind to the CLS context (both for error monitoring and for state propagation), and there are middlewares floating around for CLS that will do the same for Express / Restify and Hapi. That's probably the best way to shim this in.

Those would be shims for HTTP servers, right? What would be the recommended approach for shimming HTTP clients?

**Comment by tlivings** [comment]
Yes. And unfortunately, there is no easy way to do it for clients, since basically anyone downstream may create a new http request, not bind it to your namespace, and you're back to where you started.

**Comment by othiym23** [comment]
@leedm777 For that, refer back to my initial comment on this issue: https://github.com/othiym23/node-continuation-local-storage/issues/24#issuecomment-50726745. You need some piece of code that figures out which HTTP requests are created as part of a CLS transactional scope and then `.bindEmitter` them like any other EE. You can probably do this simply by monkeypatching `http.createClient` / `http.get` / `http.request` and having them check if whatever namespace you're using is active, calling the original function, and then calling `bindEmitter` on the returned client object before returning it back to the caller. I would point you at the code that does this in `node-newrelic`, but it's pretty baroque at this point and not likely to be very illustrative.

I think we've probably talked through this issue enough to call it as resolved as it's going to get. I'm open to adding additional helper functions to simplify getting this all set up, but the default behavior should probably stay the same as it is now, in the interests of not turning CLS into more of a CPU and GC hog than it already is.
