### ISSUE TITLE
Is unbind possible?

### ISSUE THREAD

**Issue by alexkwolfe** [othiym23/node-continuation-local-storage#32]
If I want to use a CLS context on part of an HTTP request, say just for a single Express middleware, is there a way to exit the active namespace before calling `next()`?

**Comment by alexkwolfe** [comment]
For example:

```javascript
var middleware = function(req, res, next) {
  namespace.run(function() {
    doSomethingAsync(function() {
      // exit the namespace before continuing to the next middleware
      namespace.exit();
      next();
    });
  });
};
```

**Comment by alexkwolfe** [comment]
Something like this may work:

```javascript
var middleware = function(req, res, next) {
  namespace.run(function(context) {
    doSomethingAsync(function() {
      // exit the namespace before continuing to the next middleware
      namespace.exit(context);
      next();
    });
  });
};
```

**Comment by othiym23** [comment]
That kind of low-level hackery is exactly what passing the context into the `.run()` callback was designed to support. However, I'm not sure that what you're trying to do matches what that code will actually do. Can you give me a few more words on what problem you're trying to solve?

**Comment by alexkwolfe** [comment]
Sure.

I am writing a module that records HTTP requests in the presence of an active namespace. The problem is that I want control over when the capture "session" starts and ends. Below is a test case that illustrates what I'm trying to do:

```javascript
var assert = require('chai').assert,
    request = require('request'),
    capture = require('capture'); // my module

it('should not capture transactions after exit', function (done) {
  
  // start capturing
  capture(function(ns) {

    var options = { url: 'http://localhost:8888', method: 'POST' };

    // make an HTTP request
    request(options, function() {
      
      // assert that the HTTP request/response were captured
      var transactions = ns.get('transactions');
      assert.equal(transactions.length, 1);
      
      // exit the namespace, no further capturing will take place
      ns.exit(); 

      // assert that the namespace is no longer active
      assert(!ns.active);

      // make a second request
      request(options, function() {
        
        // assert that nothing else was captured
        assert.equal(transactions.length, 1);
        
        done();
      });
    });
  });
});
```

Without the call to `ns.exit()`, the second request is captured and added to the Array of `transactions`.

I initially considered simply setting a flag in the namespace that would indicate that capturing was enabled or disabled, however, this requires additional cleanup in the namespace that would otherwise be more cleanly handled by exiting the namespace.

**Comment by othiym23** [comment]
That's not what `ns.exit()` does, and I'm a little surprised you're not getting assertion failures. If you look at [this code](https://github.com/othiym23/node-continuation-local-storage/blob/master/context.js#L103-L109) in `ns.exit()` and [this code](https://github.com/othiym23/node-continuation-local-storage/blob/master/context.js#L103-L109) in `ns.run()`, you'll see that eventually `ns.run()` is going to try to exit the context itself, and the assertion will fail because the context is no longer in the set of contexts associated with the continuation chain.

All CLS does is propagate the state along the continuation chain. I'd need to see the implementation of `capture()` to understand how it's building up the list of transactions being tracked. If you want only part of the continuation chain to be instrumented, the API you really ought to be looking at is `{add,remove}AsyncListener` in `async-listener` itself.

CLS calls `addAsyncListener` at load time, because as far as I was able to tell, exerting more fine-grained control over when the asyncListener was active made no real difference to CLS's overhead, and did add a bunch more complexity to CLS. But I think that availability to control whether async bridging is active or not is exactly what you need. The only wrinkle is that since you're removing the listener, whatever handoff you want to do of the transaction information will need to happen at the time you deactive the asyncListener, because context will no longer be propagated through the continuation chain from that point onwards.

CLS and the asyncListener API are sort of joined at the hip, but if you want to extend or modify CLS's behavior, it's important to understand which bit is responsible for which behavior. It may be that you can do everything you want to do with just the async-listener code, and hacking CLS into doing what you need may be more complicated than it would otherwise be.

**Comment by alexkwolfe** [comment]
Thank you for taking the time to write an in depth reply. 

I'm sorry. I should have explicitly said that the `ns` object passed to the `capture()` callback isn't an actual CLS namespace, but rather an object that acts rather like the CLS namespace. 

The capture module monkeys with http.ClientRequest (a la [nock](https://github.com/pgte/nock)). Any code that executes via the `capture()` callback will have its HTTP transactions recorded. And code that executes from elsewhere will not.

Below is a pretty good representation of how it works. I get that there's a lot of nasty stuff going on here, the least of which is probably hacking the `namespace.exit()` function. 

Leaving aside whether this is sane, it seems like a good use case for CLS. I want to keep a continuation-local variable (`transactions`). The problem is that I also need to be able to explicitly exit the continuation-local context so that the capture module doesn't capture too much.

```javascript
var http = require('http'),
    cls = require('continuation-local-storage'),
    namespace = cls.createNamespace('foo'),
    CapturingRequest = require('./capturing-request');

// Patch the core http module's ClientRequest. The CapturingRequest records transactions
// in namespace.transactions when namespace.active is available, otherwise it delegates
// to the original http.ClientRequest.
http.ClientRequest = CapturingRequest;

// HACK: Make the namespace's exit() function safe to call more than once.
var originalExit = namespace.exit;
namespace.exit = function(context) {
  if (context == null)
    return;
  if (namespace.active === context || namespace._set.lastIndexOf(context) >= 0)
    return originalExit.call(namespace, context);
};

// The capture module
module.exports = function(callback) {

  namespace.run(function(context) {

    // Start with an empty Array of transactions
    namespace.set("transactions", []);

    // Define the namespace to pass to the callback
    var ns = {
      get: namespace.get.bind(namespace),
      bind: namespace.bind.bind(namespace),
      exit: function() {
        // Exit out of this context. Later, CLS will also attempt to exit once
        // the callback chain has completed. Normally that would cause an assertion error
        // in CLS, but the hack above ensures that doesn't happen.
        return namespace.exit(context);
      }
    };
    
    // Make the active property which delegates to the CLS namespace.active property
    Object.defineProperty(ns, "active", {
      get: function() {
        return namespace.active;
      },
      enumerable: true
    });

    callback(ns);
  });
};
```

**Comment by othiym23** [comment]
> The problem is that I also need to be able to explicitly exit the continuation-local context so that the capture module doesn't capture too much.

This is the part I still don't think I get: why does the one thing (exiting the context) lead to the other (keeping the capture module from capturing too much)?

**Comment by alexkwolfe** [comment]
Because the `CapturingRequest` module simply looks for the namespace to be active in order to do its dirty work. If there is no active namespace, then `CapturingRequest` delegates to the standard `http.ClientRequest`.

I could accomplish the same thing by keeping a state variable in the namespace that would be switched on by the `capture()` function, and off by the `ns.exit()` function.

**Comment by othiym23** [comment]
> I could accomplish the same thing by keeping a state variable in the namespace that would be switched on by the `capture()` function, and off by the `ns.exit(`) function.

That is likely to be _far_ simpler than my other solution, although I would suggest not monkeypatching `ns.exit()` at all and just having the code that actually performs the capture use a latch like so:

```javascript
if (!ns.get("captured")) {
  ns.set("captured", "yup");
  // do capture timing or w/e here
}
```

**Comment by alexkwolfe** [comment]
Yep. Agreed. Thanks for your time on this.
