### ISSUE TITLE
Relation to theory...

### ISSUE THREAD

**Issue by jeapostrophe** [othiym23/node-continuation-local-storage#37]
This seems to be an implementation of this paper:

http://cs.brown.edu/~sk/Publications/Papers/Published/mk-int-safe-state-web/paper.pdf

Can it do the same things?

**Comment by othiym23** [comment]
That's a surprisingly hard question to answer, in part because support for full continuations and `call/cc` are absent from JavaScript for safety (or security) reasons. The answer is a qualified yes, but instead of full continuations, CLS is a pragmatic best effort to thread just some state specific to a chain of callbacks written in continuation-passing style (CPS), which works by basically monkeypatching the whole runtime to shim over the places where the continuation chain would otherwise be broken by lower-level APIs or calls into the C++ side of Node's runtime.

A full continuation-based web-serving environment is beyond the scope of CLS, but I think in practice you should be able to do most of the stuff in that paper using a framework like Express or Hapi with CLS, as long as your goal is mostly to transparently move data around, and not do some of the more exotic control-flow tricks from there.

Since I've answered your question as best as I'm able, I'm going to close this issue. Thanks for your time!

**Comment by othiym23** [comment]
Also, if you're interested in those kinds of tricks, you should look at koa and other frameworks built on using generators and Promises. It's still not as flexible as `call/cc`, because you don't get the full combination of bound environment + suspended call state that you'd get with full continuations, but it's close enough to give you a substantial amount of the power provided by frameworks built on thunks.
