### ISSUE TITLE
cannot get sequelize & cls to work together

### ISSUE THREAD

**Issue by haikyuu** [othiym23/node-continuation-local-storage#38]
How can i get cls to work with [sequelize](http://docs.sequelizejs.com/en/latest/) ?
I created a nameSpace for every request but its data is lost when sequelize is used.

Do i have to develop a shimmer or is there some **nice** workaround?

**Comment by janmeier** [comment]
You can enable CLS with sequelize by setting `Sequelize.cls = namespace` http://docs.sequelizejs.com/en/latest/docs/transactions/

This will also enable CLS with sequelize transactions - the transaction is automatically passed to every call inside the callback to `sequelize.transaction`

If you don't want the transaction CLS behaviour, you can manually apply the bluebird cls patch https://github.com/TimBeyer/cls-bluebird/

**Comment by haikyuu** [comment]
Thanks a lot @janmeier ...though i don't know how you found me here !
> This will also enable CLS with sequelize transactions

And for other than transactions?

In my use case: an express webapp, i want to trace every database query back to the user/req that was responsible for it. So i created a `namespace` for  every relevant request and i've put some data in it:

```javascript
app.use('/api', function(req, res, next) {
    number++;
    var ns = cls.createNamespace('test');
    ns.bindEmitter(req);
    ns.bindEmitter(res);

    ns.run(function() {

      ns.set('number', number);

      next();
    });
```
and in the hook side:

```javascript
hooks: {
        afterBulkDelete: function () {
          var ns = cls.getNamespace('test');
          console.log('number',ns.get('number'));
        }
```

But the namespace does not contain any data ...

**Comment by haikyuu** [comment]
I tried cls-bluebird, but with no success either:

```javascript
var cls = require('continuation-local-storage');
var ns = cls.createNamespace('testSeq');

var patcher = require('cls-bluebird');
var Sequelize = require('sequelize');
patcher(Sequelize);
var sequelize = new Sequelize(config.MYSQL_DB, config.MYSQL_USER, config.MYSQL_PASSWORD, {
  logging: false,
  host: config.MYSQL_URI,
  port: config.MYSQL_PORT
});
```
but the namespace was still empty

**Comment by janmeier** [comment]
What I meant by enable for sequelize transaction was that it enables sequelize transcations to use CLS - i.e. `sequelize.transaction` stores the transaction on the namespace, and every call inside the transaction will get the transaction from the namespace. This saves you from having to pass `{ transaction: t }` to every call.

The namespace looses data because of bluebird. Setting  `Sequelize.cls = namespace` will patch bluebird to carry over the data from that namespace across `then` calls. You get either let sequelize do it with `.cls` (and get the added functionality for transactions) or patch Sequelize.Promise yourself with the patch I linked.


I was the implementer of CLS in sequelize, and I've been subscribed to this repo ever since, thats why I saw your post ;)

**Comment by janmeier** [comment]
That's not how the patch works :)

You have to call `patcher(ns)`

Also, be aware that if you have a different version of bluebird in your own project than the one sequelize uses, your version will be patched, but sequelize's will not

**Comment by haikyuu** [comment]
> `patcher(Sequelize);`
:zzz: side effects...
Anyway, it actually worked even though not the way i expected.
I can access the namespace and its data from sequelize callbacks ... But not hooks :( 
Any idea why ?

**Comment by janmeier** [comment]
That sounds strange, we have tests for it in sequelize so it should work.

If you can wip up a small, reproducible test-case post it in the sequelize github and we can work from there
